### ISSUE TITLE
Dato *sgteDato (Lista *unaLista)

### ISSUE THREAD

**Issue by fcoJCC** [IC-ULS/edd-taller1-g3#15]
Si la lista no es vacía y actual no es el ultimo dato, retorna puntero al dato siguiente al actual en la lista, y lo establece como dato actual. De lo contrario retorna NULL.

**Comment by yieeei** [comment]
Dato *sgteDato (Lista *unaLista){
	if ((esVaciaLista(&(*unaLista))!=1) && (*unaLista)->actual!=(*unaLista)->ultimo){
		Dato DATO=(*unaLista)->actual;
		DATO=DATO->sgte;
		printf("Devolviento puntero al dato siguiente.\n");
		return (DATO);
	}
	printf("No existe el Dato siguiente\n");
	return NULL;
}
