### ISSUE TITLE
Dato *antDato (Lista *unaLista)

### ISSUE THREAD

**Issue by fcoJCC** [IC-ULS/edd-taller1-g3#16]
si la lista no es vacía y actual no es primer dato, retorna puntero al dato anterior al actual en la lista, y lo establece como dato actual. De lo contrario retorna NULL.

**Comment by yieeei** [comment]
Dato *antDato (Lista *unaLista){
	if ((esVaciaLista(&(*unaLista))!=1) && (*unaLista)->actual!=(*unaLista)->primero){
		Dato DATO=(*unaLista)->actual;
		DATO=DATO->ant;
		printf("Devolviento puntero al dato anterior.\n");
		return (DATO);
	}
	printf("No existe el Dato anterior\n");
	return NULL;
}
