### ISSUE TITLE
int esPrimerDato (Lista *unaLista)

### ISSUE THREAD

**Issue by fcoJCC** [IC-ULS/edd-taller1-g3#17]
si la lista no es vacía y el dato actual es el primero retorna 1.

**Comment by yieeei** [comment]
int esPrimerDato (Lista *unaLista){
	if ((esVaciaLista(&(*unaLista))!=0 && (*unaLista)->actual==(*unaLista)->primero)){
	printf("Si es el Primer Dato\n");
		return 1;
	}
	return 0;
}
Aquí está mi esPrimerDato
