### ISSUE TITLE
int esUltimoDato (Lista *unaLista)

### ISSUE THREAD

**Issue by fcoJCC** [IC-ULS/edd-taller1-g3#18]
si la lista no es vacía y el dato actual es el ultimo retorna 1.

**Comment by yieeei** [comment]
int esUltimoDato (Lista *unaLista){
	if ((esVaciaLista(&(*unaLista))!=0 && (*unaLista)->actual==(*unaLista)->ultimo)){
		printf("Si es el ultimo Dato");
		return 1;
	}
	return 0;
}
Aquí está mi esUltimoDato.
