### ISSUE TITLE
int recorrerLista (Lista *unaLista)

### ISSUE THREAD

**Issue by fcoJCC** [IC-ULS/edd-taller1-g3#19]
si la lista no es vacía muestra un la salida estándar cada uno de los datos almacenados en la lista. Si tiene éxito retorna 1.

**Comment by yieeei** [comment]
int mostrarLista(Lista *unaLista){
	int i;
	(*unaLista)->actual=(*unaLista)->primero;
	if ((*unaLista)->largo==0){
		printf("La Lista está vacía\n");
		return 0;
	}
	for (i=0; i<(*unaLista)->largo; i++){
		printf("%d \t %d \n", (i+1), (*unaLista)->actual->dato);
		(*unaLista)->actual=(*unaLista)->actual->sgte;	
	}
	(*unaLista)->actual=(*unaLista)->primero;
	return 1;
}

Aquí está mi recorrer lista.
